// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: habits/v1/habits.proto

package habitspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Schedule type enum
type ScheduleType int32

const (
	ScheduleType_SCHEDULE_TYPE_UNSPECIFIED ScheduleType = 0
	ScheduleType_SCHEDULE_TYPE_INTERVAL    ScheduleType = 1 // Every N days
	ScheduleType_SCHEDULE_TYPE_WEEKLY      ScheduleType = 2 // Specific days of week
)

// Enum value maps for ScheduleType.
var (
	ScheduleType_name = map[int32]string{
		0: "SCHEDULE_TYPE_UNSPECIFIED",
		1: "SCHEDULE_TYPE_INTERVAL",
		2: "SCHEDULE_TYPE_WEEKLY",
	}
	ScheduleType_value = map[string]int32{
		"SCHEDULE_TYPE_UNSPECIFIED": 0,
		"SCHEDULE_TYPE_INTERVAL":    1,
		"SCHEDULE_TYPE_WEEKLY":      2,
	}
)

func (x ScheduleType) Enum() *ScheduleType {
	p := new(ScheduleType)
	*p = x
	return p
}

func (x ScheduleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleType) Descriptor() protoreflect.EnumDescriptor {
	return file_habits_v1_habits_proto_enumTypes[0].Descriptor()
}

func (ScheduleType) Type() protoreflect.EnumType {
	return &file_habits_v1_habits_proto_enumTypes[0]
}

func (x ScheduleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleType.Descriptor instead.
func (ScheduleType) EnumDescriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{0}
}

// Habit message
type Habit struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Basic info
	Name        string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Color       *string `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"` // HEX color, e.g., "#FF5722"
	// Schedule configuration
	ScheduleType ScheduleType `protobuf:"varint,6,opt,name=schedule_type,json=scheduleType,proto3,enum=habits.v1.ScheduleType" json:"schedule_type,omitempty"`
	IntervalDays *int32       `protobuf:"varint,7,opt,name=interval_days,json=intervalDays,proto3,oneof" json:"interval_days,omitempty"` // Required for INTERVAL type (1=daily, 2=every other day, etc.)
	WeeklyDays   []int32      `protobuf:"varint,8,rep,packed,name=weekly_days,json=weeklyDays,proto3" json:"weekly_days,omitempty"`      // Required for WEEKLY type (0=Sunday, 1=Monday, ..., 6=Saturday)
	// Timezone offset in hours from UTC (-12 to +14)
	TimezoneOffsetHours int32 `protobuf:"varint,9,opt,name=timezone_offset_hours,json=timezoneOffsetHours,proto3" json:"timezone_offset_hours,omitempty"`
	// Streak state
	Streak                    int32                  `protobuf:"varint,10,opt,name=streak,proto3" json:"streak,omitempty"`
	NextDeadlineUtc           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=next_deadline_utc,json=nextDeadlineUtc,proto3" json:"next_deadline_utc,omitempty"`
	ConfirmedForCurrentPeriod bool                   `protobuf:"varint,12,opt,name=confirmed_for_current_period,json=confirmedForCurrentPeriod,proto3" json:"confirmed_for_current_period,omitempty"`
	LastConfirmedAt           *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_confirmed_at,json=lastConfirmedAt,proto3,oneof" json:"last_confirmed_at,omitempty"`
	// Metadata
	IsActive      bool                   `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Habit) Reset() {
	*x = Habit{}
	mi := &file_habits_v1_habits_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Habit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Habit) ProtoMessage() {}

func (x *Habit) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Habit.ProtoReflect.Descriptor instead.
func (*Habit) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{0}
}

func (x *Habit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Habit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Habit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Habit) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Habit) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *Habit) GetScheduleType() ScheduleType {
	if x != nil {
		return x.ScheduleType
	}
	return ScheduleType_SCHEDULE_TYPE_UNSPECIFIED
}

func (x *Habit) GetIntervalDays() int32 {
	if x != nil && x.IntervalDays != nil {
		return *x.IntervalDays
	}
	return 0
}

func (x *Habit) GetWeeklyDays() []int32 {
	if x != nil {
		return x.WeeklyDays
	}
	return nil
}

func (x *Habit) GetTimezoneOffsetHours() int32 {
	if x != nil {
		return x.TimezoneOffsetHours
	}
	return 0
}

func (x *Habit) GetStreak() int32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *Habit) GetNextDeadlineUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.NextDeadlineUtc
	}
	return nil
}

func (x *Habit) GetConfirmedForCurrentPeriod() bool {
	if x != nil {
		return x.ConfirmedForCurrentPeriod
	}
	return false
}

func (x *Habit) GetLastConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConfirmedAt
	}
	return nil
}

func (x *Habit) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Habit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Habit) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// HabitConfirmation message
type HabitConfirmation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HabitId          string                 `protobuf:"bytes,2,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConfirmedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	ConfirmedForDate string                 `protobuf:"bytes,5,opt,name=confirmed_for_date,json=confirmedForDate,proto3" json:"confirmed_for_date,omitempty"` // Date in format "YYYY-MM-DD"
	Notes            *string                `protobuf:"bytes,6,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HabitConfirmation) Reset() {
	*x = HabitConfirmation{}
	mi := &file_habits_v1_habits_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HabitConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HabitConfirmation) ProtoMessage() {}

func (x *HabitConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HabitConfirmation.ProtoReflect.Descriptor instead.
func (*HabitConfirmation) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{1}
}

func (x *HabitConfirmation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HabitConfirmation) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *HabitConfirmation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HabitConfirmation) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

func (x *HabitConfirmation) GetConfirmedForDate() string {
	if x != nil {
		return x.ConfirmedForDate
	}
	return ""
}

func (x *HabitConfirmation) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *HabitConfirmation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateHabit
type CreateHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Color         *string                `protobuf:"bytes,4,opt,name=color,proto3,oneof" json:"color,omitempty"`
	ScheduleType  ScheduleType           `protobuf:"varint,5,opt,name=schedule_type,json=scheduleType,proto3,enum=habits.v1.ScheduleType" json:"schedule_type,omitempty"`
	IntervalDays  *int32                 `protobuf:"varint,6,opt,name=interval_days,json=intervalDays,proto3,oneof" json:"interval_days,omitempty"`
	WeeklyDays    []int32                `protobuf:"varint,7,rep,packed,name=weekly_days,json=weeklyDays,proto3" json:"weekly_days,omitempty"`
	Timezone      string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"` // IANA timezone string (e.g., "Europe/Moscow", "America/New_York")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHabitRequest) Reset() {
	*x = CreateHabitRequest{}
	mi := &file_habits_v1_habits_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHabitRequest) ProtoMessage() {}

func (x *CreateHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHabitRequest.ProtoReflect.Descriptor instead.
func (*CreateHabitRequest) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateHabitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHabitRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateHabitRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *CreateHabitRequest) GetScheduleType() ScheduleType {
	if x != nil {
		return x.ScheduleType
	}
	return ScheduleType_SCHEDULE_TYPE_UNSPECIFIED
}

func (x *CreateHabitRequest) GetIntervalDays() int32 {
	if x != nil && x.IntervalDays != nil {
		return *x.IntervalDays
	}
	return 0
}

func (x *CreateHabitRequest) GetWeeklyDays() []int32 {
	if x != nil {
		return x.WeeklyDays
	}
	return nil
}

func (x *CreateHabitRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type CreateHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHabitResponse) Reset() {
	*x = CreateHabitResponse{}
	mi := &file_habits_v1_habits_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHabitResponse) ProtoMessage() {}

func (x *CreateHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHabitResponse.ProtoReflect.Descriptor instead.
func (*CreateHabitResponse) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

// GetHabit
type GetHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitRequest) Reset() {
	*x = GetHabitRequest{}
	mi := &file_habits_v1_habits_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitRequest) ProtoMessage() {}

func (x *GetHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitRequest.ProtoReflect.Descriptor instead.
func (*GetHabitRequest) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{4}
}

func (x *GetHabitRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *GetHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitResponse) Reset() {
	*x = GetHabitResponse{}
	mi := &file_habits_v1_habits_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitResponse) ProtoMessage() {}

func (x *GetHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitResponse.ProtoReflect.Descriptor instead.
func (*GetHabitResponse) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{5}
}

func (x *GetHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

// ListHabits
type ListHabitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActiveOnly    *bool                  `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3,oneof" json:"active_only,omitempty"` // Filter only active habits
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHabitsRequest) Reset() {
	*x = ListHabitsRequest{}
	mi := &file_habits_v1_habits_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHabitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHabitsRequest) ProtoMessage() {}

func (x *ListHabitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHabitsRequest.ProtoReflect.Descriptor instead.
func (*ListHabitsRequest) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{6}
}

func (x *ListHabitsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListHabitsRequest) GetActiveOnly() bool {
	if x != nil && x.ActiveOnly != nil {
		return *x.ActiveOnly
	}
	return false
}

type ListHabitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habits        []*Habit               `protobuf:"bytes,1,rep,name=habits,proto3" json:"habits,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHabitsResponse) Reset() {
	*x = ListHabitsResponse{}
	mi := &file_habits_v1_habits_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHabitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHabitsResponse) ProtoMessage() {}

func (x *ListHabitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHabitsResponse.ProtoReflect.Descriptor instead.
func (*ListHabitsResponse) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{7}
}

func (x *ListHabitsResponse) GetHabits() []*Habit {
	if x != nil {
		return x.Habits
	}
	return nil
}

func (x *ListHabitsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UpdateHabit
type UpdateHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Color         *string                `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	ScheduleType  *ScheduleType          `protobuf:"varint,6,opt,name=schedule_type,json=scheduleType,proto3,enum=habits.v1.ScheduleType,oneof" json:"schedule_type,omitempty"`
	IntervalDays  *int32                 `protobuf:"varint,7,opt,name=interval_days,json=intervalDays,proto3,oneof" json:"interval_days,omitempty"`
	WeeklyDays    []int32                `protobuf:"varint,8,rep,packed,name=weekly_days,json=weeklyDays,proto3" json:"weekly_days,omitempty"` // Empty array means no update
	Timezone      *string                `protobuf:"bytes,9,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`                         // IANA timezone string (service will convert to offset)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHabitRequest) Reset() {
	*x = UpdateHabitRequest{}
	mi := &file_habits_v1_habits_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHabitRequest) ProtoMessage() {}

func (x *UpdateHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHabitRequest.ProtoReflect.Descriptor instead.
func (*UpdateHabitRequest) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateHabitRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *UpdateHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateHabitRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateHabitRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateHabitRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateHabitRequest) GetScheduleType() ScheduleType {
	if x != nil && x.ScheduleType != nil {
		return *x.ScheduleType
	}
	return ScheduleType_SCHEDULE_TYPE_UNSPECIFIED
}

func (x *UpdateHabitRequest) GetIntervalDays() int32 {
	if x != nil && x.IntervalDays != nil {
		return *x.IntervalDays
	}
	return 0
}

func (x *UpdateHabitRequest) GetWeeklyDays() []int32 {
	if x != nil {
		return x.WeeklyDays
	}
	return nil
}

func (x *UpdateHabitRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

type UpdateHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHabitResponse) Reset() {
	*x = UpdateHabitResponse{}
	mi := &file_habits_v1_habits_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHabitResponse) ProtoMessage() {}

func (x *UpdateHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHabitResponse.ProtoReflect.Descriptor instead.
func (*UpdateHabitResponse) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

// DeleteHabit
type DeleteHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHabitRequest) Reset() {
	*x = DeleteHabitRequest{}
	mi := &file_habits_v1_habits_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHabitRequest) ProtoMessage() {}

func (x *DeleteHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHabitRequest.ProtoReflect.Descriptor instead.
func (*DeleteHabitRequest) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteHabitRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *DeleteHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHabitResponse) Reset() {
	*x = DeleteHabitResponse{}
	mi := &file_habits_v1_habits_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHabitResponse) ProtoMessage() {}

func (x *DeleteHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHabitResponse.ProtoReflect.Descriptor instead.
func (*DeleteHabitResponse) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteHabitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ConfirmHabit
type ConfirmHabitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	Notes         *string                `protobuf:"bytes,3,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmHabitRequest) Reset() {
	*x = ConfirmHabitRequest{}
	mi := &file_habits_v1_habits_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmHabitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmHabitRequest) ProtoMessage() {}

func (x *ConfirmHabitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmHabitRequest.ProtoReflect.Descriptor instead.
func (*ConfirmHabitRequest) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmHabitRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *ConfirmHabitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmHabitRequest) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

type ConfirmHabitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Habit         *Habit                 `protobuf:"bytes,1,opt,name=habit,proto3" json:"habit,omitempty"` // Updated habit with incremented streak
	Confirmation  *HabitConfirmation     `protobuf:"bytes,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmHabitResponse) Reset() {
	*x = ConfirmHabitResponse{}
	mi := &file_habits_v1_habits_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmHabitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmHabitResponse) ProtoMessage() {}

func (x *ConfirmHabitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmHabitResponse.ProtoReflect.Descriptor instead.
func (*ConfirmHabitResponse) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{13}
}

func (x *ConfirmHabitResponse) GetHabit() *Habit {
	if x != nil {
		return x.Habit
	}
	return nil
}

func (x *ConfirmHabitResponse) GetConfirmation() *HabitConfirmation {
	if x != nil {
		return x.Confirmation
	}
	return nil
}

// GetHabitHistory
type GetHabitHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`          // Default 30
	Offset        *int32                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`        // For pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitHistoryRequest) Reset() {
	*x = GetHabitHistoryRequest{}
	mi := &file_habits_v1_habits_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitHistoryRequest) ProtoMessage() {}

func (x *GetHabitHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHabitHistoryRequest) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{14}
}

func (x *GetHabitHistoryRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *GetHabitHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHabitHistoryRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetHabitHistoryRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetHabitHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmations []*HabitConfirmation   `protobuf:"bytes,1,rep,name=confirmations,proto3" json:"confirmations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitHistoryResponse) Reset() {
	*x = GetHabitHistoryResponse{}
	mi := &file_habits_v1_habits_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitHistoryResponse) ProtoMessage() {}

func (x *GetHabitHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHabitHistoryResponse) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{15}
}

func (x *GetHabitHistoryResponse) GetConfirmations() []*HabitConfirmation {
	if x != nil {
		return x.Confirmations
	}
	return nil
}

func (x *GetHabitHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetHabitStats
type GetHabitStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HabitId       string                 `protobuf:"bytes,1,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHabitStatsRequest) Reset() {
	*x = GetHabitStatsRequest{}
	mi := &file_habits_v1_habits_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitStatsRequest) ProtoMessage() {}

func (x *GetHabitStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitStatsRequest.ProtoReflect.Descriptor instead.
func (*GetHabitStatsRequest) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{16}
}

func (x *GetHabitStatsRequest) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *GetHabitStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHabitStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CurrentStreak      int32                  `protobuf:"varint,1,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	LongestStreak      int32                  `protobuf:"varint,2,opt,name=longest_streak,json=longestStreak,proto3" json:"longest_streak,omitempty"`
	TotalConfirmations int32                  `protobuf:"varint,3,opt,name=total_confirmations,json=totalConfirmations,proto3" json:"total_confirmations,omitempty"`
	CompletionRate     float64                `protobuf:"fixed64,4,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"` // Percentage (0-100)
	FirstConfirmation  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_confirmation,json=firstConfirmation,proto3" json:"first_confirmation,omitempty"`
	LastConfirmation   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_confirmation,json=lastConfirmation,proto3" json:"last_confirmation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetHabitStatsResponse) Reset() {
	*x = GetHabitStatsResponse{}
	mi := &file_habits_v1_habits_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHabitStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitStatsResponse) ProtoMessage() {}

func (x *GetHabitStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habits_v1_habits_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitStatsResponse.ProtoReflect.Descriptor instead.
func (*GetHabitStatsResponse) Descriptor() ([]byte, []int) {
	return file_habits_v1_habits_proto_rawDescGZIP(), []int{17}
}

func (x *GetHabitStatsResponse) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *GetHabitStatsResponse) GetLongestStreak() int32 {
	if x != nil {
		return x.LongestStreak
	}
	return 0
}

func (x *GetHabitStatsResponse) GetTotalConfirmations() int32 {
	if x != nil {
		return x.TotalConfirmations
	}
	return 0
}

func (x *GetHabitStatsResponse) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *GetHabitStatsResponse) GetFirstConfirmation() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstConfirmation
	}
	return nil
}

func (x *GetHabitStatsResponse) GetLastConfirmation() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConfirmation
	}
	return nil
}

var File_habits_v1_habits_proto protoreflect.FileDescriptor

const file_habits_v1_habits_proto_rawDesc = "" +
	"\n" +
	"\x16habits/v1/habits.proto\x12\thabits.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x06\n" +
	"\x05Habit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x01R\x05color\x88\x01\x01\x12<\n" +
	"\rschedule_type\x18\x06 \x01(\x0e2\x17.habits.v1.ScheduleTypeR\fscheduleType\x12(\n" +
	"\rinterval_days\x18\a \x01(\x05H\x02R\fintervalDays\x88\x01\x01\x12\x1f\n" +
	"\vweekly_days\x18\b \x03(\x05R\n" +
	"weeklyDays\x122\n" +
	"\x15timezone_offset_hours\x18\t \x01(\x05R\x13timezoneOffsetHours\x12\x16\n" +
	"\x06streak\x18\n" +
	" \x01(\x05R\x06streak\x12F\n" +
	"\x11next_deadline_utc\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0fnextDeadlineUtc\x12?\n" +
	"\x1cconfirmed_for_current_period\x18\f \x01(\bR\x19confirmedForCurrentPeriod\x12K\n" +
	"\x11last_confirmed_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x0flastConfirmedAt\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_colorB\x10\n" +
	"\x0e_interval_daysB\x14\n" +
	"\x12_last_confirmed_at\"\xa4\x02\n" +
	"\x11HabitConfirmation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bhabit_id\x18\x02 \x01(\tR\ahabitId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12=\n" +
	"\fconfirmed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\x12,\n" +
	"\x12confirmed_for_date\x18\x05 \x01(\tR\x10confirmedForDate\x12\x19\n" +
	"\x05notes\x18\x06 \x01(\tH\x00R\x05notes\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\b\n" +
	"\x06_notes\"\xd4\x02\n" +
	"\x12CreateHabitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x04 \x01(\tH\x01R\x05color\x88\x01\x01\x12<\n" +
	"\rschedule_type\x18\x05 \x01(\x0e2\x17.habits.v1.ScheduleTypeR\fscheduleType\x12(\n" +
	"\rinterval_days\x18\x06 \x01(\x05H\x02R\fintervalDays\x88\x01\x01\x12\x1f\n" +
	"\vweekly_days\x18\a \x03(\x05R\n" +
	"weeklyDays\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezoneB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_colorB\x10\n" +
	"\x0e_interval_days\"=\n" +
	"\x13CreateHabitResponse\x12&\n" +
	"\x05habit\x18\x01 \x01(\v2\x10.habits.v1.HabitR\x05habit\"E\n" +
	"\x0fGetHabitRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\":\n" +
	"\x10GetHabitResponse\x12&\n" +
	"\x05habit\x18\x01 \x01(\v2\x10.habits.v1.HabitR\x05habit\"b\n" +
	"\x11ListHabitsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\vactive_only\x18\x02 \x01(\bH\x00R\n" +
	"activeOnly\x88\x01\x01B\x0e\n" +
	"\f_active_only\"_\n" +
	"\x12ListHabitsResponse\x12(\n" +
	"\x06habits\x18\x01 \x03(\v2\x10.habits.v1.HabitR\x06habits\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa6\x03\n" +
	"\x12UpdateHabitRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x02R\x05color\x88\x01\x01\x12A\n" +
	"\rschedule_type\x18\x06 \x01(\x0e2\x17.habits.v1.ScheduleTypeH\x03R\fscheduleType\x88\x01\x01\x12(\n" +
	"\rinterval_days\x18\a \x01(\x05H\x04R\fintervalDays\x88\x01\x01\x12\x1f\n" +
	"\vweekly_days\x18\b \x03(\x05R\n" +
	"weeklyDays\x12\x1f\n" +
	"\btimezone\x18\t \x01(\tH\x05R\btimezone\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_colorB\x10\n" +
	"\x0e_schedule_typeB\x10\n" +
	"\x0e_interval_daysB\v\n" +
	"\t_timezone\"=\n" +
	"\x13UpdateHabitResponse\x12&\n" +
	"\x05habit\x18\x01 \x01(\v2\x10.habits.v1.HabitR\x05habit\"H\n" +
	"\x12DeleteHabitRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x13DeleteHabitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"n\n" +
	"\x13ConfirmHabitRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\x05notes\x18\x03 \x01(\tH\x00R\x05notes\x88\x01\x01B\b\n" +
	"\x06_notes\"\x80\x01\n" +
	"\x14ConfirmHabitResponse\x12&\n" +
	"\x05habit\x18\x01 \x01(\v2\x10.habits.v1.HabitR\x05habit\x12@\n" +
	"\fconfirmation\x18\x02 \x01(\v2\x1c.habits.v1.HabitConfirmationR\fconfirmation\"\x99\x01\n" +
	"\x16GetHabitHistoryRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"~\n" +
	"\x17GetHabitHistoryResponse\x12B\n" +
	"\rconfirmations\x18\x01 \x03(\v2\x1c.habits.v1.HabitConfirmationR\rconfirmations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"J\n" +
	"\x14GetHabitStatsRequest\x12\x19\n" +
	"\bhabit_id\x18\x01 \x01(\tR\ahabitId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xd3\x02\n" +
	"\x15GetHabitStatsResponse\x12%\n" +
	"\x0ecurrent_streak\x18\x01 \x01(\x05R\rcurrentStreak\x12%\n" +
	"\x0elongest_streak\x18\x02 \x01(\x05R\rlongestStreak\x12/\n" +
	"\x13total_confirmations\x18\x03 \x01(\x05R\x12totalConfirmations\x12'\n" +
	"\x0fcompletion_rate\x18\x04 \x01(\x01R\x0ecompletionRate\x12I\n" +
	"\x12first_confirmation\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x11firstConfirmation\x12G\n" +
	"\x11last_confirmation\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastConfirmation*c\n" +
	"\fScheduleType\x12\x1d\n" +
	"\x19SCHEDULE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SCHEDULE_TYPE_INTERVAL\x10\x01\x12\x18\n" +
	"\x14SCHEDULE_TYPE_WEEKLY\x10\x022\x87\x05\n" +
	"\fHabitService\x12L\n" +
	"\vCreateHabit\x12\x1d.habits.v1.CreateHabitRequest\x1a\x1e.habits.v1.CreateHabitResponse\x12C\n" +
	"\bGetHabit\x12\x1a.habits.v1.GetHabitRequest\x1a\x1b.habits.v1.GetHabitResponse\x12I\n" +
	"\n" +
	"ListHabits\x12\x1c.habits.v1.ListHabitsRequest\x1a\x1d.habits.v1.ListHabitsResponse\x12L\n" +
	"\vUpdateHabit\x12\x1d.habits.v1.UpdateHabitRequest\x1a\x1e.habits.v1.UpdateHabitResponse\x12L\n" +
	"\vDeleteHabit\x12\x1d.habits.v1.DeleteHabitRequest\x1a\x1e.habits.v1.DeleteHabitResponse\x12O\n" +
	"\fConfirmHabit\x12\x1e.habits.v1.ConfirmHabitRequest\x1a\x1f.habits.v1.ConfirmHabitResponse\x12X\n" +
	"\x0fGetHabitHistory\x12!.habits.v1.GetHabitHistoryRequest\x1a\".habits.v1.GetHabitHistoryResponse\x12R\n" +
	"\rGetHabitStats\x12\x1f.habits.v1.GetHabitStatsRequest\x1a .habits.v1.GetHabitStatsResponseB)Z'habits-service/proto/habits/v1;habitspbb\x06proto3"

var (
	file_habits_v1_habits_proto_rawDescOnce sync.Once
	file_habits_v1_habits_proto_rawDescData []byte
)

func file_habits_v1_habits_proto_rawDescGZIP() []byte {
	file_habits_v1_habits_proto_rawDescOnce.Do(func() {
		file_habits_v1_habits_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_habits_v1_habits_proto_rawDesc), len(file_habits_v1_habits_proto_rawDesc)))
	})
	return file_habits_v1_habits_proto_rawDescData
}

var file_habits_v1_habits_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_habits_v1_habits_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_habits_v1_habits_proto_goTypes = []any{
	(ScheduleType)(0),               // 0: habits.v1.ScheduleType
	(*Habit)(nil),                   // 1: habits.v1.Habit
	(*HabitConfirmation)(nil),       // 2: habits.v1.HabitConfirmation
	(*CreateHabitRequest)(nil),      // 3: habits.v1.CreateHabitRequest
	(*CreateHabitResponse)(nil),     // 4: habits.v1.CreateHabitResponse
	(*GetHabitRequest)(nil),         // 5: habits.v1.GetHabitRequest
	(*GetHabitResponse)(nil),        // 6: habits.v1.GetHabitResponse
	(*ListHabitsRequest)(nil),       // 7: habits.v1.ListHabitsRequest
	(*ListHabitsResponse)(nil),      // 8: habits.v1.ListHabitsResponse
	(*UpdateHabitRequest)(nil),      // 9: habits.v1.UpdateHabitRequest
	(*UpdateHabitResponse)(nil),     // 10: habits.v1.UpdateHabitResponse
	(*DeleteHabitRequest)(nil),      // 11: habits.v1.DeleteHabitRequest
	(*DeleteHabitResponse)(nil),     // 12: habits.v1.DeleteHabitResponse
	(*ConfirmHabitRequest)(nil),     // 13: habits.v1.ConfirmHabitRequest
	(*ConfirmHabitResponse)(nil),    // 14: habits.v1.ConfirmHabitResponse
	(*GetHabitHistoryRequest)(nil),  // 15: habits.v1.GetHabitHistoryRequest
	(*GetHabitHistoryResponse)(nil), // 16: habits.v1.GetHabitHistoryResponse
	(*GetHabitStatsRequest)(nil),    // 17: habits.v1.GetHabitStatsRequest
	(*GetHabitStatsResponse)(nil),   // 18: habits.v1.GetHabitStatsResponse
	(*timestamppb.Timestamp)(nil),   // 19: google.protobuf.Timestamp
}
var file_habits_v1_habits_proto_depIdxs = []int32{
	0,  // 0: habits.v1.Habit.schedule_type:type_name -> habits.v1.ScheduleType
	19, // 1: habits.v1.Habit.next_deadline_utc:type_name -> google.protobuf.Timestamp
	19, // 2: habits.v1.Habit.last_confirmed_at:type_name -> google.protobuf.Timestamp
	19, // 3: habits.v1.Habit.created_at:type_name -> google.protobuf.Timestamp
	19, // 4: habits.v1.Habit.updated_at:type_name -> google.protobuf.Timestamp
	19, // 5: habits.v1.HabitConfirmation.confirmed_at:type_name -> google.protobuf.Timestamp
	19, // 6: habits.v1.HabitConfirmation.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: habits.v1.CreateHabitRequest.schedule_type:type_name -> habits.v1.ScheduleType
	1,  // 8: habits.v1.CreateHabitResponse.habit:type_name -> habits.v1.Habit
	1,  // 9: habits.v1.GetHabitResponse.habit:type_name -> habits.v1.Habit
	1,  // 10: habits.v1.ListHabitsResponse.habits:type_name -> habits.v1.Habit
	0,  // 11: habits.v1.UpdateHabitRequest.schedule_type:type_name -> habits.v1.ScheduleType
	1,  // 12: habits.v1.UpdateHabitResponse.habit:type_name -> habits.v1.Habit
	1,  // 13: habits.v1.ConfirmHabitResponse.habit:type_name -> habits.v1.Habit
	2,  // 14: habits.v1.ConfirmHabitResponse.confirmation:type_name -> habits.v1.HabitConfirmation
	2,  // 15: habits.v1.GetHabitHistoryResponse.confirmations:type_name -> habits.v1.HabitConfirmation
	19, // 16: habits.v1.GetHabitStatsResponse.first_confirmation:type_name -> google.protobuf.Timestamp
	19, // 17: habits.v1.GetHabitStatsResponse.last_confirmation:type_name -> google.protobuf.Timestamp
	3,  // 18: habits.v1.HabitService.CreateHabit:input_type -> habits.v1.CreateHabitRequest
	5,  // 19: habits.v1.HabitService.GetHabit:input_type -> habits.v1.GetHabitRequest
	7,  // 20: habits.v1.HabitService.ListHabits:input_type -> habits.v1.ListHabitsRequest
	9,  // 21: habits.v1.HabitService.UpdateHabit:input_type -> habits.v1.UpdateHabitRequest
	11, // 22: habits.v1.HabitService.DeleteHabit:input_type -> habits.v1.DeleteHabitRequest
	13, // 23: habits.v1.HabitService.ConfirmHabit:input_type -> habits.v1.ConfirmHabitRequest
	15, // 24: habits.v1.HabitService.GetHabitHistory:input_type -> habits.v1.GetHabitHistoryRequest
	17, // 25: habits.v1.HabitService.GetHabitStats:input_type -> habits.v1.GetHabitStatsRequest
	4,  // 26: habits.v1.HabitService.CreateHabit:output_type -> habits.v1.CreateHabitResponse
	6,  // 27: habits.v1.HabitService.GetHabit:output_type -> habits.v1.GetHabitResponse
	8,  // 28: habits.v1.HabitService.ListHabits:output_type -> habits.v1.ListHabitsResponse
	10, // 29: habits.v1.HabitService.UpdateHabit:output_type -> habits.v1.UpdateHabitResponse
	12, // 30: habits.v1.HabitService.DeleteHabit:output_type -> habits.v1.DeleteHabitResponse
	14, // 31: habits.v1.HabitService.ConfirmHabit:output_type -> habits.v1.ConfirmHabitResponse
	16, // 32: habits.v1.HabitService.GetHabitHistory:output_type -> habits.v1.GetHabitHistoryResponse
	18, // 33: habits.v1.HabitService.GetHabitStats:output_type -> habits.v1.GetHabitStatsResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_habits_v1_habits_proto_init() }
func file_habits_v1_habits_proto_init() {
	if File_habits_v1_habits_proto != nil {
		return
	}
	file_habits_v1_habits_proto_msgTypes[0].OneofWrappers = []any{}
	file_habits_v1_habits_proto_msgTypes[1].OneofWrappers = []any{}
	file_habits_v1_habits_proto_msgTypes[2].OneofWrappers = []any{}
	file_habits_v1_habits_proto_msgTypes[6].OneofWrappers = []any{}
	file_habits_v1_habits_proto_msgTypes[8].OneofWrappers = []any{}
	file_habits_v1_habits_proto_msgTypes[12].OneofWrappers = []any{}
	file_habits_v1_habits_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_habits_v1_habits_proto_rawDesc), len(file_habits_v1_habits_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_habits_v1_habits_proto_goTypes,
		DependencyIndexes: file_habits_v1_habits_proto_depIdxs,
		EnumInfos:         file_habits_v1_habits_proto_enumTypes,
		MessageInfos:      file_habits_v1_habits_proto_msgTypes,
	}.Build()
	File_habits_v1_habits_proto = out.File
	file_habits_v1_habits_proto_goTypes = nil
	file_habits_v1_habits_proto_depIdxs = nil
}
