// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: habits/v1/habits.proto

package habitspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HabitService_CreateHabit_FullMethodName     = "/habits.v1.HabitService/CreateHabit"
	HabitService_GetHabit_FullMethodName        = "/habits.v1.HabitService/GetHabit"
	HabitService_ListHabits_FullMethodName      = "/habits.v1.HabitService/ListHabits"
	HabitService_UpdateHabit_FullMethodName     = "/habits.v1.HabitService/UpdateHabit"
	HabitService_DeleteHabit_FullMethodName     = "/habits.v1.HabitService/DeleteHabit"
	HabitService_ConfirmHabit_FullMethodName    = "/habits.v1.HabitService/ConfirmHabit"
	HabitService_GetHabitHistory_FullMethodName = "/habits.v1.HabitService/GetHabitHistory"
	HabitService_GetHabitStats_FullMethodName   = "/habits.v1.HabitService/GetHabitStats"
)

// HabitServiceClient is the client API for HabitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HabitService provides habit management functionality
type HabitServiceClient interface {
	// CreateHabit creates a new habit
	CreateHabit(ctx context.Context, in *CreateHabitRequest, opts ...grpc.CallOption) (*CreateHabitResponse, error)
	// GetHabit retrieves a habit by ID
	GetHabit(ctx context.Context, in *GetHabitRequest, opts ...grpc.CallOption) (*GetHabitResponse, error)
	// ListHabits retrieves all habits for a user
	ListHabits(ctx context.Context, in *ListHabitsRequest, opts ...grpc.CallOption) (*ListHabitsResponse, error)
	// UpdateHabit updates a habit
	UpdateHabit(ctx context.Context, in *UpdateHabitRequest, opts ...grpc.CallOption) (*UpdateHabitResponse, error)
	// DeleteHabit soft deletes a habit
	DeleteHabit(ctx context.Context, in *DeleteHabitRequest, opts ...grpc.CallOption) (*DeleteHabitResponse, error)
	// ConfirmHabit confirms habit completion for current period
	ConfirmHabit(ctx context.Context, in *ConfirmHabitRequest, opts ...grpc.CallOption) (*ConfirmHabitResponse, error)
	// GetHabitHistory retrieves confirmation history for a habit
	GetHabitHistory(ctx context.Context, in *GetHabitHistoryRequest, opts ...grpc.CallOption) (*GetHabitHistoryResponse, error)
	// GetHabitStats retrieves statistics for a habit
	GetHabitStats(ctx context.Context, in *GetHabitStatsRequest, opts ...grpc.CallOption) (*GetHabitStatsResponse, error)
}

type habitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHabitServiceClient(cc grpc.ClientConnInterface) HabitServiceClient {
	return &habitServiceClient{cc}
}

func (c *habitServiceClient) CreateHabit(ctx context.Context, in *CreateHabitRequest, opts ...grpc.CallOption) (*CreateHabitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHabitResponse)
	err := c.cc.Invoke(ctx, HabitService_CreateHabit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) GetHabit(ctx context.Context, in *GetHabitRequest, opts ...grpc.CallOption) (*GetHabitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHabitResponse)
	err := c.cc.Invoke(ctx, HabitService_GetHabit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) ListHabits(ctx context.Context, in *ListHabitsRequest, opts ...grpc.CallOption) (*ListHabitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHabitsResponse)
	err := c.cc.Invoke(ctx, HabitService_ListHabits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) UpdateHabit(ctx context.Context, in *UpdateHabitRequest, opts ...grpc.CallOption) (*UpdateHabitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHabitResponse)
	err := c.cc.Invoke(ctx, HabitService_UpdateHabit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) DeleteHabit(ctx context.Context, in *DeleteHabitRequest, opts ...grpc.CallOption) (*DeleteHabitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHabitResponse)
	err := c.cc.Invoke(ctx, HabitService_DeleteHabit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) ConfirmHabit(ctx context.Context, in *ConfirmHabitRequest, opts ...grpc.CallOption) (*ConfirmHabitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmHabitResponse)
	err := c.cc.Invoke(ctx, HabitService_ConfirmHabit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) GetHabitHistory(ctx context.Context, in *GetHabitHistoryRequest, opts ...grpc.CallOption) (*GetHabitHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHabitHistoryResponse)
	err := c.cc.Invoke(ctx, HabitService_GetHabitHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) GetHabitStats(ctx context.Context, in *GetHabitStatsRequest, opts ...grpc.CallOption) (*GetHabitStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHabitStatsResponse)
	err := c.cc.Invoke(ctx, HabitService_GetHabitStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HabitServiceServer is the server API for HabitService service.
// All implementations must embed UnimplementedHabitServiceServer
// for forward compatibility.
//
// HabitService provides habit management functionality
type HabitServiceServer interface {
	// CreateHabit creates a new habit
	CreateHabit(context.Context, *CreateHabitRequest) (*CreateHabitResponse, error)
	// GetHabit retrieves a habit by ID
	GetHabit(context.Context, *GetHabitRequest) (*GetHabitResponse, error)
	// ListHabits retrieves all habits for a user
	ListHabits(context.Context, *ListHabitsRequest) (*ListHabitsResponse, error)
	// UpdateHabit updates a habit
	UpdateHabit(context.Context, *UpdateHabitRequest) (*UpdateHabitResponse, error)
	// DeleteHabit soft deletes a habit
	DeleteHabit(context.Context, *DeleteHabitRequest) (*DeleteHabitResponse, error)
	// ConfirmHabit confirms habit completion for current period
	ConfirmHabit(context.Context, *ConfirmHabitRequest) (*ConfirmHabitResponse, error)
	// GetHabitHistory retrieves confirmation history for a habit
	GetHabitHistory(context.Context, *GetHabitHistoryRequest) (*GetHabitHistoryResponse, error)
	// GetHabitStats retrieves statistics for a habit
	GetHabitStats(context.Context, *GetHabitStatsRequest) (*GetHabitStatsResponse, error)
	mustEmbedUnimplementedHabitServiceServer()
}

// UnimplementedHabitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHabitServiceServer struct{}

func (UnimplementedHabitServiceServer) CreateHabit(context.Context, *CreateHabitRequest) (*CreateHabitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHabit not implemented")
}
func (UnimplementedHabitServiceServer) GetHabit(context.Context, *GetHabitRequest) (*GetHabitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHabit not implemented")
}
func (UnimplementedHabitServiceServer) ListHabits(context.Context, *ListHabitsRequest) (*ListHabitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHabits not implemented")
}
func (UnimplementedHabitServiceServer) UpdateHabit(context.Context, *UpdateHabitRequest) (*UpdateHabitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHabit not implemented")
}
func (UnimplementedHabitServiceServer) DeleteHabit(context.Context, *DeleteHabitRequest) (*DeleteHabitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHabit not implemented")
}
func (UnimplementedHabitServiceServer) ConfirmHabit(context.Context, *ConfirmHabitRequest) (*ConfirmHabitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmHabit not implemented")
}
func (UnimplementedHabitServiceServer) GetHabitHistory(context.Context, *GetHabitHistoryRequest) (*GetHabitHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHabitHistory not implemented")
}
func (UnimplementedHabitServiceServer) GetHabitStats(context.Context, *GetHabitStatsRequest) (*GetHabitStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHabitStats not implemented")
}
func (UnimplementedHabitServiceServer) mustEmbedUnimplementedHabitServiceServer() {}
func (UnimplementedHabitServiceServer) testEmbeddedByValue()                      {}

// UnsafeHabitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HabitServiceServer will
// result in compilation errors.
type UnsafeHabitServiceServer interface {
	mustEmbedUnimplementedHabitServiceServer()
}

func RegisterHabitServiceServer(s grpc.ServiceRegistrar, srv HabitServiceServer) {
	// If the following call pancis, it indicates UnimplementedHabitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HabitService_ServiceDesc, srv)
}

func _HabitService_CreateHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).CreateHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_CreateHabit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).CreateHabit(ctx, req.(*CreateHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_GetHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).GetHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_GetHabit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).GetHabit(ctx, req.(*GetHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_ListHabits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHabitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).ListHabits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_ListHabits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).ListHabits(ctx, req.(*ListHabitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_UpdateHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).UpdateHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_UpdateHabit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).UpdateHabit(ctx, req.(*UpdateHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_DeleteHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).DeleteHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_DeleteHabit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).DeleteHabit(ctx, req.(*DeleteHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_ConfirmHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).ConfirmHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_ConfirmHabit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).ConfirmHabit(ctx, req.(*ConfirmHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_GetHabitHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHabitHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).GetHabitHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_GetHabitHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).GetHabitHistory(ctx, req.(*GetHabitHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_GetHabitStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHabitStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).GetHabitStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HabitService_GetHabitStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).GetHabitStats(ctx, req.(*GetHabitStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HabitService_ServiceDesc is the grpc.ServiceDesc for HabitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HabitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "habits.v1.HabitService",
	HandlerType: (*HabitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHabit",
			Handler:    _HabitService_CreateHabit_Handler,
		},
		{
			MethodName: "GetHabit",
			Handler:    _HabitService_GetHabit_Handler,
		},
		{
			MethodName: "ListHabits",
			Handler:    _HabitService_ListHabits_Handler,
		},
		{
			MethodName: "UpdateHabit",
			Handler:    _HabitService_UpdateHabit_Handler,
		},
		{
			MethodName: "DeleteHabit",
			Handler:    _HabitService_DeleteHabit_Handler,
		},
		{
			MethodName: "ConfirmHabit",
			Handler:    _HabitService_ConfirmHabit_Handler,
		},
		{
			MethodName: "GetHabitHistory",
			Handler:    _HabitService_GetHabitHistory_Handler,
		},
		{
			MethodName: "GetHabitStats",
			Handler:    _HabitService_GetHabitStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "habits/v1/habits.proto",
}
