// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: events/v1/events.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType defines the type of event
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED                  EventType = 0
	EventType_EVENT_TYPE_USER_REGISTERED              EventType = 1
	EventType_EVENT_TYPE_EMAIL_VERIFICATION_REQUESTED EventType = 2
	EventType_EVENT_TYPE_PASSWORD_RESET_REQUESTED     EventType = 3
	EventType_EVENT_TYPE_PASSWORD_CHANGED             EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_USER_REGISTERED",
		2: "EVENT_TYPE_EMAIL_VERIFICATION_REQUESTED",
		3: "EVENT_TYPE_PASSWORD_RESET_REQUESTED",
		4: "EVENT_TYPE_PASSWORD_CHANGED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":                  0,
		"EVENT_TYPE_USER_REGISTERED":              1,
		"EVENT_TYPE_EMAIL_VERIFICATION_REQUESTED": 2,
		"EVENT_TYPE_PASSWORD_RESET_REQUESTED":     3,
		"EVENT_TYPE_PASSWORD_CHANGED":             4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_events_v1_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{0}
}

// NotificationType defines the type of notification to send
type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_EMAIL       NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_SMS         NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_PUSH        NotificationType = 3
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_EMAIL",
		2: "NOTIFICATION_TYPE_SMS",
		3: "NOTIFICATION_TYPE_PUSH",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"NOTIFICATION_TYPE_EMAIL":       1,
		"NOTIFICATION_TYPE_SMS":         2,
		"NOTIFICATION_TYPE_PUSH":        3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_events_proto_enumTypes[1].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_events_v1_events_proto_enumTypes[1]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{1}
}

// UserRegisteredEvent is published when a new user registers
type UserRegisteredEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username          string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FirstName         string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	VerificationToken string                 `protobuf:"bytes,5,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	Timezone          string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserRegisteredEvent) Reset() {
	*x = UserRegisteredEvent{}
	mi := &file_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisteredEvent) ProtoMessage() {}

func (x *UserRegisteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisteredEvent.ProtoReflect.Descriptor instead.
func (*UserRegisteredEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegisteredEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegisteredEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegisteredEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserRegisteredEvent) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserRegisteredEvent) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *UserRegisteredEvent) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserRegisteredEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// EmailVerificationRequestedEvent is published when email verification is requested
type EmailVerificationRequestedEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	VerificationToken string                 `protobuf:"bytes,3,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	RequestedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmailVerificationRequestedEvent) Reset() {
	*x = EmailVerificationRequestedEvent{}
	mi := &file_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerificationRequestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerificationRequestedEvent) ProtoMessage() {}

func (x *EmailVerificationRequestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerificationRequestedEvent.ProtoReflect.Descriptor instead.
func (*EmailVerificationRequestedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *EmailVerificationRequestedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EmailVerificationRequestedEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailVerificationRequestedEvent) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *EmailVerificationRequestedEvent) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

// PasswordResetRequestedEvent is published when password reset is requested
type PasswordResetRequestedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ResetToken    string                 `protobuf:"bytes,3,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetRequestedEvent) Reset() {
	*x = PasswordResetRequestedEvent{}
	mi := &file_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetRequestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetRequestedEvent) ProtoMessage() {}

func (x *PasswordResetRequestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetRequestedEvent.ProtoReflect.Descriptor instead.
func (*PasswordResetRequestedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *PasswordResetRequestedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PasswordResetRequestedEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordResetRequestedEvent) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

func (x *PasswordResetRequestedEvent) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

// PasswordChangedEvent is published when password is changed or reset
type PasswordChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	WasReset      bool                   `protobuf:"varint,4,opt,name=was_reset,json=wasReset,proto3" json:"was_reset,omitempty"` // true if changed via reset, false if changed via change password
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordChangedEvent) Reset() {
	*x = PasswordChangedEvent{}
	mi := &file_events_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordChangedEvent) ProtoMessage() {}

func (x *PasswordChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordChangedEvent.ProtoReflect.Descriptor instead.
func (*PasswordChangedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *PasswordChangedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PasswordChangedEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordChangedEvent) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

func (x *PasswordChangedEvent) GetWasReset() bool {
	if x != nil {
		return x.WasReset
	}
	return false
}

// Event wrapper that contains all event types
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType EventType              `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=events.v1.EventType" json:"event_type,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_UserRegistered
	//	*Event_EmailVerificationRequested
	//	*Event_PasswordResetRequested
	//	*Event_PasswordChanged
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetUserRegistered() *UserRegisteredEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_UserRegistered); ok {
			return x.UserRegistered
		}
	}
	return nil
}

func (x *Event) GetEmailVerificationRequested() *EmailVerificationRequestedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_EmailVerificationRequested); ok {
			return x.EmailVerificationRequested
		}
	}
	return nil
}

func (x *Event) GetPasswordResetRequested() *PasswordResetRequestedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_PasswordResetRequested); ok {
			return x.PasswordResetRequested
		}
	}
	return nil
}

func (x *Event) GetPasswordChanged() *PasswordChangedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_PasswordChanged); ok {
			return x.PasswordChanged
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_UserRegistered struct {
	UserRegistered *UserRegisteredEvent `protobuf:"bytes,10,opt,name=user_registered,json=userRegistered,proto3,oneof"`
}

type Event_EmailVerificationRequested struct {
	EmailVerificationRequested *EmailVerificationRequestedEvent `protobuf:"bytes,11,opt,name=email_verification_requested,json=emailVerificationRequested,proto3,oneof"`
}

type Event_PasswordResetRequested struct {
	PasswordResetRequested *PasswordResetRequestedEvent `protobuf:"bytes,12,opt,name=password_reset_requested,json=passwordResetRequested,proto3,oneof"`
}

type Event_PasswordChanged struct {
	PasswordChanged *PasswordChangedEvent `protobuf:"bytes,13,opt,name=password_changed,json=passwordChanged,proto3,oneof"`
}

func (*Event_UserRegistered) isEvent_Payload() {}

func (*Event_EmailVerificationRequested) isEvent_Payload() {}

func (*Event_PasswordResetRequested) isEvent_Payload() {}

func (*Event_PasswordChanged) isEvent_Payload() {}

var File_events_v1_events_proto protoreflect.FileDescriptor

const file_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16events/v1/events.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\x13UserRegisteredEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12-\n" +
	"\x12verification_token\x18\x05 \x01(\tR\x11verificationToken\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbe\x01\n" +
	"\x1fEmailVerificationRequestedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12-\n" +
	"\x12verification_token\x18\x03 \x01(\tR\x11verificationToken\x12=\n" +
	"\frequested_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\xac\x01\n" +
	"\x1bPasswordResetRequestedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1f\n" +
	"\vreset_token\x18\x03 \x01(\tR\n" +
	"resetToken\x12=\n" +
	"\frequested_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\x9d\x01\n" +
	"\x14PasswordChangedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x129\n" +
	"\n" +
	"changed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\x12\x1b\n" +
	"\twas_reset\x18\x04 \x01(\bR\bwasReset\"\x89\x04\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x123\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x14.events.v1.EventTypeR\teventType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12I\n" +
	"\x0fuser_registered\x18\n" +
	" \x01(\v2\x1e.events.v1.UserRegisteredEventH\x00R\x0euserRegistered\x12n\n" +
	"\x1cemail_verification_requested\x18\v \x01(\v2*.events.v1.EmailVerificationRequestedEventH\x00R\x1aemailVerificationRequested\x12b\n" +
	"\x18password_reset_requested\x18\f \x01(\v2&.events.v1.PasswordResetRequestedEventH\x00R\x16passwordResetRequested\x12L\n" +
	"\x10password_changed\x18\r \x01(\v2\x1f.events.v1.PasswordChangedEventH\x00R\x0fpasswordChangedB\t\n" +
	"\apayload*\xbe\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEVENT_TYPE_USER_REGISTERED\x10\x01\x12+\n" +
	"'EVENT_TYPE_EMAIL_VERIFICATION_REQUESTED\x10\x02\x12'\n" +
	"#EVENT_TYPE_PASSWORD_RESET_REQUESTED\x10\x03\x12\x1f\n" +
	"\x1bEVENT_TYPE_PASSWORD_CHANGED\x10\x04*\x89\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_EMAIL\x10\x01\x12\x19\n" +
	"\x15NOTIFICATION_TYPE_SMS\x10\x02\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_PUSH\x10\x03B/Z-notification-service/proto/events/v1;eventspbb\x06proto3"

var (
	file_events_v1_events_proto_rawDescOnce sync.Once
	file_events_v1_events_proto_rawDescData []byte
)

func file_events_v1_events_proto_rawDescGZIP() []byte {
	file_events_v1_events_proto_rawDescOnce.Do(func() {
		file_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_events_proto_rawDesc), len(file_events_v1_events_proto_rawDesc)))
	})
	return file_events_v1_events_proto_rawDescData
}

var file_events_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_events_v1_events_proto_goTypes = []any{
	(EventType)(0),                          // 0: events.v1.EventType
	(NotificationType)(0),                   // 1: events.v1.NotificationType
	(*UserRegisteredEvent)(nil),             // 2: events.v1.UserRegisteredEvent
	(*EmailVerificationRequestedEvent)(nil), // 3: events.v1.EmailVerificationRequestedEvent
	(*PasswordResetRequestedEvent)(nil),     // 4: events.v1.PasswordResetRequestedEvent
	(*PasswordChangedEvent)(nil),            // 5: events.v1.PasswordChangedEvent
	(*Event)(nil),                           // 6: events.v1.Event
	(*timestamppb.Timestamp)(nil),           // 7: google.protobuf.Timestamp
}
var file_events_v1_events_proto_depIdxs = []int32{
	7,  // 0: events.v1.UserRegisteredEvent.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: events.v1.EmailVerificationRequestedEvent.requested_at:type_name -> google.protobuf.Timestamp
	7,  // 2: events.v1.PasswordResetRequestedEvent.requested_at:type_name -> google.protobuf.Timestamp
	7,  // 3: events.v1.PasswordChangedEvent.changed_at:type_name -> google.protobuf.Timestamp
	0,  // 4: events.v1.Event.event_type:type_name -> events.v1.EventType
	7,  // 5: events.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 6: events.v1.Event.user_registered:type_name -> events.v1.UserRegisteredEvent
	3,  // 7: events.v1.Event.email_verification_requested:type_name -> events.v1.EmailVerificationRequestedEvent
	4,  // 8: events.v1.Event.password_reset_requested:type_name -> events.v1.PasswordResetRequestedEvent
	5,  // 9: events.v1.Event.password_changed:type_name -> events.v1.PasswordChangedEvent
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_events_v1_events_proto_init() }
func file_events_v1_events_proto_init() {
	if File_events_v1_events_proto != nil {
		return
	}
	file_events_v1_events_proto_msgTypes[4].OneofWrappers = []any{
		(*Event_UserRegistered)(nil),
		(*Event_EmailVerificationRequested)(nil),
		(*Event_PasswordResetRequested)(nil),
		(*Event_PasswordChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_events_proto_rawDesc), len(file_events_v1_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_events_proto_goTypes,
		DependencyIndexes: file_events_v1_events_proto_depIdxs,
		EnumInfos:         file_events_v1_events_proto_enumTypes,
		MessageInfos:      file_events_v1_events_proto_msgTypes,
	}.Build()
	File_events_v1_events_proto = out.File
	file_events_v1_events_proto_goTypes = nil
	file_events_v1_events_proto_depIdxs = nil
}
